version: '3'
services:
  app:
    container_name: pillpack-data-server
    restart: always
    build: .
    volumes:
        - .:/mycode
    environment:
        - MONGO_URI=mongodb://mongo:27017
    ports:
    - "80:3030"
    links:
        - mongo
  mongo:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
